# Generated by Django 4.0 on 2021-12-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfase', models.CharField(max_length=254)),
                ('data', models.DateField()),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('anexo', models.CharField(max_length=254)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma', verbose_name='turma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.planejamento', verbose_name='planejamento')),
            ],
        ),
    ]
