# Generated by Django 4.0 on 2021-12-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='turno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
