# Generated by Django 4.0 on 2021-12-20 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_remove_planejamento_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 20, 0, 30, 9, 914645), null=True),
        ),
    ]
