# Generated by Django 4.0 on 2021-12-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_planejamento_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 14, 50, 34, 918981), null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 22, 14, 50, 34, 919906), null=True),
        ),
    ]
