# Generated by Django 4.0 on 2021-12-22 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('aulas', '0005_alter_planejamento_data_envio_alter_resposta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 18, 47, 30, 718955), null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 22, 18, 47, 30, 719833), null=True),
        ),
    ]
