# Generated by Django 4.0 on 2021-12-22 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_alter_planejamento_data_envio_alter_resposta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='visto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='visto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 19, 20, 50, 202775), null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 19, 20, 50, 203522), null=True),
        ),
    ]
