# Generated by Django 4.0 on 2022-01-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0018_alter_planejamento_data_envio_alter_resposta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 15, 7, 29, 99763), null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 15, 7, 29, 100647), null=True),
        ),
    ]
