# Generated by Django 4.0 on 2022-02-10 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0023_alter_planejamento_data_envio_alter_resposta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 12, 51, 0, 343852), null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 10, 12, 51, 0, 344560), null=True),
        ),
    ]
