# Generated by Django 4.0 on 2022-02-16 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0024_alter_planejamento_data_envio_alter_resposta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planejamento',
            old_name='anexo',
            new_name='tema',
        ),
        migrations.RemoveField(
            model_name='planejamento',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='planejamento',
            name='objetivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 7, 33, 18, 468344), null=True),
        ),
    ]
