# Generated by Django 4.0 on 2022-02-16 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0029_alter_resposta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 8, 9, 21, 562745), null=True),
        ),
    ]
