# Generated by Django 4.0 on 2022-02-23 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_formacao_alter_usuario_grupo_and_more'),
        ('turmas', '0007_alter_escola_unidade_alter_turma_escola'),
        ('aulas', '0031_alter_resposta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emphasis', models.CharField(choices=[('T', 'Técnico'), ('P', 'Propedêutico')], max_length=1)),
                ('lesson_date', models.DateField()),
                ('document', models.CharField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turmas.turma', verbose_name='classe')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='posted_by')),
            ],
        ),
        migrations.CreateModel(
            name='GradePlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=254)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 20, 8, 44, 677101), null=True)),
                ('class_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.gradeplan', verbose_name='grade_plan_comment')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='posted_by')),
            ],
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='planejamento',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Planejamento',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
