# Generated by Django 4.0 on 2022-02-24 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_alter_escola_unidade_alter_turma_escola'),
        ('aulas', '0032_gradeplan_gradeplancomment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeplan',
            old_name='lesson_date',
            new_name='lesson_month',
        ),
        migrations.RemoveField(
            model_name='gradeplan',
            name='emphasis',
        ),
        migrations.RemoveField(
            model_name='gradeplan',
            name='grade',
        ),
        migrations.AddField(
            model_name='gradeplan',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='turmas.escola', verbose_name='school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 12, 4, 26, 566606), null=True),
        ),
    ]
