# Generated by Django 4.0 on 2022-02-24 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0033_rename_lesson_date_gradeplan_lesson_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeplan',
            name='viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='gradeplancomment',
            name='viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 15, 48, 12, 829125), null=True),
        ),
    ]
