# Generated by Django 4.0 on 2022-02-26 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0034_gradeplan_viewed_gradeplancomment_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 13, 3, 54, 154453), null=True),
        ),
    ]
