# Generated by Django 4.0 on 2022-02-26 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0035_alter_gradeplancomment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeplan',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 20, 9, 19, 817523), null=True),
        ),
    ]
