# Generated by Django 4.0 on 2022-03-03 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0038_alter_gradeplancomment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 23, 40, 933572), null=True),
        ),
    ]
