# Generated by Django 4.0 on 2022-03-04 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0039_alter_gradeplancomment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeplancomment',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 10, 7, 52, 106132), null=True),
        ),
    ]
