# Generated by Django 4.0 on 2021-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='nome',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='plano_1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='plano_2',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='programacao',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='turma',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.CharField(max_length=254),
        ),
    ]
