# Generated by Django 4.0 on 2022-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0003_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='complemento',
            name='video',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
