# Generated by Django 4.0 on 2022-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0004_complemento_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complemento',
            name='arquivo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
