# Generated by Django 4.0 on 2021-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=254),
        ),
    ]
