# Generated by Django 4.0 on 2022-02-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_formacao_alter_usuario_grupo_and_more'),
        ('turmas', '0004_escola_observacao_turma_livro_turma_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='professor'),
        ),
    ]
