# Generated by Django 4.0 on 2022-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_alter_escola_unidade_alter_turma_escola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='livro',
            new_name='dia_aula',
        ),
        migrations.AddField(
            model_name='turma',
            name='livro_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='livro_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
