# Generated by Django 4.0 on 2022-03-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_remove_turma_quantidade_alunos_courseware_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ordem_aula',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
