# Generated by Django 4.0 on 2021-12-31 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=254)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 31, 14, 17, 53, 535492), null=True)),
                ('visto', models.BooleanField(blank=True, default=False, null=True)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_usuario', to='usuarios.usuario')),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
