# Generated by Django 4.0 on 2021-12-31 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 31, 17, 58, 13, 665588), null=True),
        ),
    ]
