# Generated by Django 4.0 on 2021-12-31 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_chat_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='data_str',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 31, 18, 12, 29, 438178), null=True),
        ),
    ]
