# Generated by Django 4.0 on 2022-01-14 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_chat_data_str_alter_chat_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 10, 45, 11, 661522), null=True),
        ),
    ]
