# Generated by Django 4.0 on 2021-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segmentos',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
