# Generated by Django 4.0 on 2021-12-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_segmentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, default='../media/usuarios/default_user.jpeg', max_length=254, null=True),
        ),
    ]
