# Generated by Django 4.0 on 2021-12-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, default='../media/Usuarios/default_user.jpeg', max_length=254, null=True),
        ),
    ]
