# Generated by Django 4.0 on 2022-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='formacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
